# Site settings
title: Samantha Glocker
description: Systems Engineer | Serial Entrepreneur | Complex Problem Solver
url: "https://samanthaglocker.io"  # Replace with your actual domain if different
baseurl: ""  # Leave this empty if your site is at the root of your domain

# Build settings
markdown: kramdown
theme: minima  # You can change this to another theme if you prefer

# GitHub metadata settings
repository: sammilucia/sammilucia.github.io
github: [metadata]

# Collections
collections:
  articles:
	output: true
	permalink: /articles/:name

# Defaults
defaults:
  - scope:
	  path: ""
	  type: "articles"
	values:
	  layout: "article"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
