# site settings
title: Samantha Glocker
description: Systems Engineer | Serial Entrepreneur | Complex Problem Solver
url: "https://sammilucia.github.io"
baseurl: ""  # leave blank if site is in root folder

# build settings
markdown: kramdown
theme: minima

# GitHub metadata settings
repository: sammilucia/sammilucia.github.io

collections:
  articles:
    output: true
    permalink: /articles/:name

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
