markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  articles:
    output: true
    permalink: /articles/:title/

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"